### ISSUE TITLE
Only eBanking option is available. I lost all other option after updating to new SDK.

### ISSUE THREAD

**Issue by elxjitendra** [khalti/whmcs-khaltigateway-plugin#8]
<img width="403" alt="Screenshot 2023-01-18 at 11 19 31 PM" src="https://user-images.githubusercontent.com/8425962/213253653-23720189-a0a4-403f-b558-c193387f30f8.png">

**Comment by arnavshrestha404** [comment]
Same issue, I can't see any options to enable wallet payment and mobile banking.

**Comment by mnidesh** [comment]
You need to contact Khalti support to have other options including wallet payment, enabled.

**Comment by acpmasquerade** [comment]
This is an operational issue ant not necessarily the SDK version issue. You need to reach out to our merchant support department for the fix. 

Considering this, I am closing this issue report.
